name: dyte_videocll
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  dio: ^5.4.2+1
  connectivity_plus: ^6.0.1
  permission_handler: ^11.3.1
  flutter: 
    sdk: flutter
  dyte_uikit: ^0.6.2

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

